export const predefinedTags = [
  'API Integration',
  'Accessibility',
  'Analytics',
  'Authentication',
  'Backlog',
  'Beta',
  'Bug',
  'Bug Fix',
  'Cloud',
  'Deployment',
  'Design',
  'Development',
  'Documentation',
  'Emergency',
  'Feature',
  'Follow-up',
  'Hotfix',
  'Improvement',
  'Iteration',
  'Maintenance',
  'Mobile Optimization',
  'Payment Integration',
  'Performance',
  'Performance Optimization',
  'Refactoring',
  'Research',
  'Responsive Design',
  'Review',
  'SEO Optimization',
  'Scalability',
  'Search Functionality',
  'Security',
  'Security Enhancements',
  'Sprint 1',
  'Sprint 2',
  'Task',
  'Test Case',
  'Testing',
  'UI/UX',
  'User Interface',
  'User Testing',
];
